name: Deploy NEXT.js App to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Get in honey pot forms
      run: |
        cd honeypotforms
    - name: Install dependencies
      run: |
        npm ci

    - name: Start the app
      run: |
        npm run build
        npm start &

    - name: Install Cypress
      run: |
        npm install cypress

    - name: Run Cypress tests
      run: |
        npx cypress run --browser chrome --headless